### PR TITLE
Replaced: np to jnp; onp to np

### PR DESCRIPTION
**Pull request by kancurochat**
Replaced all np references to jnp and onp to np.

### CODE REVIEW

**Comment by rlouf** [comment]
That was fast! The CI breaks because it looks like `black` would have reformatted a few files. You can install the dev requirements with `pip install -r requirements-dev.txt` and then run `black mcx tests`.

The CI performs the same checks as when you do `make lint` with the following GNUMakefile: https://github.com/rlouf/mcx/blob/master/Makefile

**Comment by kancurochat** [comment]
Alright! As soon as I get home, I'll check it with black!

**Comment by balancap** [comment]
Thanks! I wanted to ask about this update too :)

**Comment by rlouf** [comment]
That looks great! Could you squash your commits before I merge?

@balancap That's the convention the JAX team is using now. See why here: https://github.com/google/jax/issues/4643

**Comment by rlouf** [comment]
Merged! Thanks for taking the time to replace all these before it becomes unmanageable 😅

**Pull request merged**
