### PR TITLE
Fix/Updates to Gamma and Poisson Distributions

### PR DESCRIPTION
**Pull request by mkretsch327**
Was experimenting with a small Gamma-Poisson model, and found some things to update. Added some additional tests too. Look forward to hearing feedback!

### CODE REVIEW

**Comment by rlouf** [comment]
Thank you for helping with this, so many distributions to implement! If you have time, would you mind implementing shape tests for the Gamma distribution? It is *critical* in PPLs (c.f. PyMC3 and its shape issues); it is useful in joint and predictive sampling, but also for inference since the initial state is obtained by sampling from the joint distribution.

**Comment by rlouf** [comment]
I see that you added tests for the sampling shape, thank you! Is it good to merge on your end?

**Comment by mkretsch327** [comment]
Hey @rlouf apologies for the delay, good on my end !

**Comment by rlouf** [comment]
Looks good to me, thank you for contributing!

**Pull request merged**
